### ISSUE TITLE
ParseCommandLineArgument Bug

### ISSUE THREAD

**Issue by Alistair-Bell** [Alistair-Bell/Mage-Engine#8]
Parsing in two of the same arguments will cause the program to crash 

Traceback (most recent call last):
  File "BuildEngine.py", line 152, in <module>
    Main()  
  File "BuildEngine.py", line 65, in Main
    arguments = UseCommandLineArguments()
  File "BuildEngine.py", line 56, in UseCommandLineArguments
    arguments = ParseCommandLineArgument(parsing, CommandLineOptions, ScriptHelp)
  File "Utility.py", line 165, in ParseCommandLineArgument
    requiredKeys.remove(lowerBound)
ValueError: list.remove(x): x not in list

TODO:
Fix error

**Comment by Alistair-Bell** [comment]
Fixed in commit https://github.com/Alistair-Bell/Mage-Engine/commit/01910a26f5fbeca64fd93e72dac0fe988cdc95fd, no longer an issue
